DROP DATABASE IF EXISTS BALAMBEH;
CREATE DATABASE BALAMBEH;
USE BALAMBEH;

-- 1. Tabla de Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NOMBREUSER VARCHAR(30) UNIQUE NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL
);

-- 2. Tabla de Conductores
CREATE TABLE CONDUCTORES (
    ID_CONDUCTOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL,
    LOCALIDAD VARCHAR(30) NOT NULL,
    RFC VARCHAR(13) UNIQUE NOT NULL,
    NUMERO VARCHAR(15) UNIQUE NOT NULL,
    VEHICULO VARCHAR(30) NOT NULL,
    AÑO_VEHICULO YEAR,
    TIPO_VEHICULO VARCHAR(30),
    TARJETA_CIRCULACION_URL VARCHAR(255) NULL
);

-- 3. Tabla RUTAS
CREATE TABLE RUTAS (
    ID_RUTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_RUTA VARCHAR(100) NOT NULL,
    ORIGEN VARCHAR(50) NOT NULL,
    DESTINO VARCHAR(50) NOT NULL
);

-- 4. Tabla PARADAS_RUTA
CREATE TABLE PARADAS_RUTA (
    ID_PARADA INT AUTO_INCREMENT PRIMARY KEY,
    ID_RUTA INT NOT NULL,
    NOMBRE_PUEBLO VARCHAR(50) NOT NULL,
    ORDEN INT NOT NULL,
    FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA)
);

-- 5. Tabla VIAJES_ACTIVOS
CREATE TABLE VIAJES_ACTIVOS (
    ID_VIAJE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CONDUCTOR INT NOT NULL,
    ID_RUTA INT NOT NULL,
    LATITUD DOUBLE NOT NULL,
    LONGITUD DOUBLE NOT NULL,
    ESTADO ENUM('ESPERANDO', 'EN_CAMINO', 'LLENO') DEFAULT 'ESPERANDO',
    ULTIMA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTORES(ID_CONDUCTOR),
    FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA)
);

CREATE TABLE SOLICITUDES (
    ID_SOLICITUD INT AUTO_INCREMENT PRIMARY KEY,
    ID_VIAJE INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(100),
    ESTADO ENUM('PENDIENTE', 'ACEPTADO', 'RECHAZADO') DEFAULT 'PENDIENTE',
    FOREIGN KEY (ID_VIAJE) REFERENCES VIAJES_ACTIVOS(ID_VIAJE)
);


-- ==========================================================
-- DML (Inserción de Datos)
-- ==========================================================
DELETE FROM SOLICITUDES;
DELETE FROM VIAJES_ACTIVOS;
DELETE FROM PARADAS_RUTA;
DELETE FROM RUTAS;
ALTER TABLE RUTAS AUTO_INCREMENT = 1;

-- 2. INSERTAR RUTAS
INSERT INTO RUTAS (ID_RUTA, NOMBRE_RUTA, ORIGEN, DESTINO) 
VALUES 
(1, 'Ruta: Peto - Mérida (Vía Corta)', 'Peto', 'Mérida'),
(2, 'Ruta: Tekax - Ticul - Muna', 'Tekax', 'Muna'),
(3, 'Ruta: Oxkutzcab - Mérida (Directo)', 'Oxkutzcab', 'Mérida'),
(4, 'Ruta: Tzucacab - Tekax', 'Tzucacab', 'Tekax');

-- 3. INSERTAR LAS PARADAS
-- --- Paradas de Ruta 1 ---
INSERT INTO PARADAS_RUTA (ID_RUTA, NOMBRE_PUEBLO, ORDEN) VALUES 
(1, 'Peto', 1), (1, 'Tzucacab', 2), (1, 'Tekax', 3), (1, 'Akil', 4), (1, 'Oxkutzcab', 5), 
(1, 'Mani', 6), (1, 'Teabo', 7), (1, 'Mérida', 8);

-- --- Paradas de Ruta 2 ---
INSERT INTO PARADAS_RUTA (ID_RUTA, NOMBRE_PUEBLO, ORDEN) VALUES 
(2, 'Tekax', 1), (2, 'Akil', 2), (2, 'Oxkutzcab', 3), (2, 'Yotholin', 4), 
(2, 'Pustunich', 5), (2, 'Ticul', 6), (2, 'Santa Elena', 7), (2, 'Muna', 8);

-- --- Paradas de Ruta 3 ---
INSERT INTO PARADAS_RUTA (ID_RUTA, NOMBRE_PUEBLO, ORDEN) VALUES 
(3, 'Oxkutzcab', 1), (3, 'Ticul', 2), (3, 'Muna', 3), (3, 'Uman', 4), (3, 'Mérida', 5);

-- --- Paradas de Ruta 4 ---
INSERT INTO PARADAS_RUTA (ID_RUTA, NOMBRE_PUEBLO, ORDEN) VALUES 
(4, 'Tzucacab', 1), (4, 'Catmís', 2), (4, 'Xaya', 3), (4, 'Tekax', 4);


ALTER TABLE PARADAS_RUTA ADD COLUMN LATITUD DOUBLE DEFAULT 0;
ALTER TABLE PARADAS_RUTA ADD COLUMN LONGITUD DOUBLE DEFAULT 0;

-- 2. Actualizamos las coordenadas de los pueblos principales
-- Zona Peto / Tzucacab
UPDATE PARADAS_RUTA SET LATITUD = 20.1275, LONGITUD = -88.9264 WHERE NOMBRE_PUEBLO = 'Peto';
UPDATE PARADAS_RUTA SET LATITUD = 20.0717, LONGITUD = -89.0519 WHERE NOMBRE_PUEBLO = 'Tzucacab';
UPDATE PARADAS_RUTA SET LATITUD = 19.9660, LONGITUD = -88.9500 WHERE NOMBRE_PUEBLO = 'Catmís';

-- Zona Tekax / Akil / Ox
UPDATE PARADAS_RUTA SET LATITUD = 20.2045, LONGITUD = -89.2835 WHERE NOMBRE_PUEBLO = 'Tekax';
UPDATE PARADAS_RUTA SET LATITUD = 20.1330, LONGITUD = -89.1330 WHERE NOMBRE_PUEBLO = 'Xaya';
UPDATE PARADAS_RUTA SET LATITUD = 20.2647, LONGITUD = -89.3494 WHERE NOMBRE_PUEBLO = 'Akil';
UPDATE PARADAS_RUTA SET LATITUD = 20.3064, LONGITUD = -89.4194 WHERE NOMBRE_PUEBLO = 'Oxkutzcab';
UPDATE PARADAS_RUTA SET LATITUD = 20.3420, LONGITUD = -89.4670 WHERE NOMBRE_PUEBLO = 'Yotholin';

-- Zona Ticul / Muna
UPDATE PARADAS_RUTA SET LATITUD = 20.3986, LONGITUD = -89.5333 WHERE NOMBRE_PUEBLO = 'Ticul';
UPDATE PARADAS_RUTA SET LATITUD = 20.3700, LONGITUD = -89.5000 WHERE NOMBRE_PUEBLO = 'Pustunich';
UPDATE PARADAS_RUTA SET LATITUD = 20.4883, LONGITUD = -89.7153 WHERE NOMBRE_PUEBLO = 'Muna';
UPDATE PARADAS_RUTA SET LATITUD = 20.3220, LONGITUD = -89.6430 WHERE NOMBRE_PUEBLO = 'Santa Elena';

-- Zona Norte / Mérida
UPDATE PARADAS_RUTA SET LATITUD = 20.3933, LONGITUD = -89.3925 WHERE NOMBRE_PUEBLO = 'Mani';
UPDATE PARADAS_RUTA SET LATITUD = 20.4022, LONGITUD = -89.2839 WHERE NOMBRE_PUEBLO = 'Teabo';
UPDATE PARADAS_RUTA SET LATITUD = 20.8833, LONGITUD = -89.7500 WHERE NOMBRE_PUEBLO = 'Uman';
UPDATE PARADAS_RUTA SET LATITUD = 20.9674, LONGITUD = -89.5926 WHERE NOMBRE_PUEBLO = 'Mérida';

-- Verificar
SELECT * FROM RUTAS;
SELECT * FROM PARADAS_RUTA;