DROP DATABASE IF EXISTS BALAMBEH; 

CREATE DATABASE BALAMBEH;

USE BALAMBEH;

-- 1. Tabla de Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NOMBREUSER VARCHAR(30) UNIQUE NOT NULL,
    -- CORRECTO: Tamaño para el hash de seguridad
    CONTRASEÑA VARCHAR(255) NOT NULL 
);

-- 2. Tabla de Conductores
CREATE TABLE CONDUCTORES (
    ID_CONDUCTOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    -- CRÍTICO: Tamaño para el hash de seguridad
    CONTRASEÑA VARCHAR(255) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL, 
    LOCALIDAD VARCHAR(30) NOT NULL,
    RFC VARCHAR(13) UNIQUE NOT NULL,
    NUMERO VARCHAR(15) UNIQUE NOT NULL,
    VEHICULO VARCHAR(30) NOT NULL,
    AÑO_VEHICULO YEAR,
    TIPO_VEHICULO VARCHAR(30),
    TARJETA_CIRCULACION_URL VARCHAR(255) NULL
);